apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:latest
          ports:
            - containerPort: 80
              name: http
            - containerPort: 22
              name: ssh
          env:
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                external_url 'http://gitlab.gitlab.svc.cluster.local'
                gitlab_rails['initial_root_password'] = 'P@ssw0rd123!'
                puma['worker_processes'] = 0
                sidekiq['max_concurrency'] = 5
                prometheus_monitoring['enable'] = false
                gitlab_rails['env'] = { 'MALLOC_CONF' => 'dirty_decay_ms:1000,muzzy_decay_ms:1000' }
                gitaly['configuration'] = { concurrency: [{ rpc: '/gitaly.SmartHTTPService/PostReceivePack', max_per_repo: 3 }] }
          resources:
            requests:
              cpu: 200m
              memory: 2Gi
            limits:
              memory: 3Gi
          volumeMounts:
            - name: gitlab-data
              mountPath: /var/opt/gitlab
            - name: gitlab-config
              mountPath: /etc/gitlab
      volumes:
        - name: gitlab-data
          emptyDir: {}
        - name: gitlab-config
          emptyDir: {}
