# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "debian/bullseye64"
 # ==========================================
  # Single Machine: The Server (Control Plane)
  # ==========================================
  config.vm.define "zihirriS" do |control|
    control.vm.hostname = "zihirriS"
    control.vm.network "private_network", ip: "192.168.56.110"
    
    control.vm.provider "virtualbox" do |vb|
      vb.name = "zihirriS"
      vb.memory = "512"
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end

    control.vm.provision "shell", path: "scripts/server.sh"
  end
end